# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Cyberneura.Astragal
PackageVersion: 0.8.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/cyberneura/astragal/releases/download/v0.8.0/Astragal_0.8.0_x64-setup.exe
  InstallerSha256: 63670452E3E759BD5D9C18A268FD93D1BF0667D4C58048385785D4C53C3B0221
  ProductCode: Astragal
  AppsAndFeaturesEntries:
  - DisplayName: Astragal
    Publisher: cyberneura
    DisplayVersion: 0.8.0
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Astragal'
ManifestType: installer
ManifestVersion: 1.12.0
